source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'YLBAweme_Example' do
  pod 'YLBAweme', :path => '../'
  #基础库
  pod 'YLBCommon', :git => 'https://github.com/ProBobo/YLBCommon.git'
  pod 'YLBModule', :git => 'https://github.com/ProBobo/YLBModule.git'
  #资源库
  pod 'YLBAwemeResource', :git => 'https://github.com/YuliboTeam/YLBAwemeResource.git'
  #第三方库
  pod 'GKPageScrollView' , :git => 'https://github.com/QuintGao/GKPageScrollView.git'
  target 'YLBAweme_Tests' do
    inherit! :search_paths

    
  end
end
